CREATE DATABASE IF NOT EXISTS tcg_pack_opener_dev;

USE tcg_pack_opener_dev;

CREATE TABLE IF NOT EXISTS trading_cards (
   id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
   card_number INT NOT NULL,
   name VARCHAR(255) NOT NULL,
   rarity VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_cards
    ON trading_cards (card_number, name, rarity);

INSERT IGNORE INTO trading_cards (card_number, name, rarity)
VALUES (8, 'Reinhardt', 'COMMON'),
       (8, 'Reinhardt', 'RARE'),
       (8, 'Reinhardt', 'ULTRA_RARE'),
       (9, 'Reinhardt', 'COMMON'),
       (9, 'Reinhardt', 'RARE'),
       (9, 'Reinhardt', 'ULTRA_RARE'),
       (11, 'Roadhog', 'COMMON'),
       (11, 'Roadhog', 'RARE'),
       (11, 'Roadhog', 'ULTRA_RARE'),
       (12, 'Roadhog', 'COMMON'),
       (12, 'Roadhog', 'RARE'),
       (12, 'Roadhog', 'ULTRA_RARE'),
       (14, 'Sigma', 'COMMON'),
       (14, 'Sigma', 'RARE'),
       (14, 'Sigma', 'ULTRA_RARE'),
       (16, 'Sigma', 'COMMON'),
       (16, 'Sigma', 'RARE'),
       (16, 'Sigma', 'ULTRA_RARE'),
       (17, 'Winston', 'COMMON'),
       (17, 'Winston', 'RARE'),
       (17, 'Winston', 'ULTRA_RARE'),
       (18, 'Winston', 'COMMON'),
       (18, 'Winston', 'RARE'),
       (18, 'Winston', 'ULTRA_RARE'),
       (27, 'Ashe', 'COMMON'),
       (27, 'Ashe', 'RARE'),
       (27, 'Ashe', 'ULTRA_RARE'),
       (28, 'Bob', 'COMMON'),
       (28, 'Bob', 'RARE'),
       (28, 'Bob', 'ULTRA_RARE'),
       (30, 'Bastion', 'COMMON'),
       (30, 'Bastion', 'RARE'),
       (30, 'Bastion', 'ULTRA_RARE'),
       (34, 'Cassidy', 'COMMON'),
       (34, 'Cassidy', 'RARE'),
       (34, 'Cassidy', 'ULTRA_RARE'),
       (41, 'Genji', 'COMMON'),
       (41, 'Genji', 'RARE'),
       (41, 'Genji', 'ULTRA_RARE'),
       (42, 'Genji', 'COMMON'),
       (42, 'Genji', 'RARE'),
       (42, 'Genji', 'ULTRA_RARE'),
       (43, 'Genji', 'ULTRA_RARE'),
       (46, 'Hanzo', 'COMMON'),
       (46, 'Hanzo', 'RARE'),
       (46, 'Hanzo', 'ULTRA_RARE'),
       (47, 'Junkrat', 'COMMON'),
       (47, 'Junkrat', 'RARE'),
       (47, 'Junkrat', 'ULTRA_RARE'),
       (63, 'Sombra', 'COMMON'),
       (63, 'Sombra', 'RARE'),
       (63, 'Sombra', 'ULTRA_RARE'),
       (65, 'Sombra', 'COMMON'),
       (65, 'Sombra', 'RARE'),
       (65, 'Sombra', 'ULTRA_RARE'),
       (68, 'Sentry Turret', 'COMMON'),
       (68, 'Sentry Turret', 'RARE'),
       (68, 'Sentry Turret', 'ULTRA_RARE'),
       (69, 'Torbjorn', 'COMMON'),
       (69, 'Torbjorn', 'RARE'),
       (69, 'Torbjorn', 'ULTRA_RARE'),
       (71, 'Deploy Turret', 'COMMON'),
       (71, 'Deploy Turret', 'RARE'),
       (71, 'Deploy Turret', 'ULTRA_RARE'),
       (72, 'Tracer', 'COMMON'),
       (72, 'Tracer', 'RARE'),
       (72, 'Tracer', 'ULTRA_RARE'),
       (74, 'Tracer', 'COMMON'),
       (74, 'Tracer', 'RARE'),
       (74, 'Tracer', 'ULTRA_RARE'),
       (77, 'Widowmaker', 'COMMON'),
       (77, 'Widowmaker', 'RARE'),
       (77, 'Widowmaker', 'ULTRA_RARE'),
       (78, 'Ana', 'COMMON'),
       (78, 'Ana', 'RARE'),
       (78, 'Ana', 'ULTRA_RARE'),
       (82, 'Baptiste', 'COMMON'),
       (82, 'Baptiste', 'RARE'),
       (82, 'Baptiste', 'ULTRA_RARE'),
       (85, 'Brigitte', 'COMMON'),
       (85, 'Brigitte', 'RARE'),
       (85, 'Brigitte', 'ULTRA_RARE'),
       (88, 'Lucio', 'COMMON'),
       (88, 'Lucio', 'RARE'),
       (88, 'Lucio', 'ULTRA_RARE'),
       (90, 'Mercy', 'COMMON'),
       (90, 'Mercy', 'RARE'),
       (90, 'Mercy', 'ULTRA_RARE'),
       (96, 'Zenyatta', 'COMMON'),
       (96, 'Zenyatta', 'RARE'),
       (96, 'Zenyatta', 'ULTRA_RARE'),
       (100, 'Ilios', 'COMMON'),
       (100, 'Ilios', 'RARE'),
       (100, 'Ilios', 'ULTRA_RARE'),
       (101, 'Hanamura', 'COMMON'),
       (101, 'Hanamura', 'RARE'),
       (101, 'Hanamura', 'ULTRA_RARE'),
       (102, 'Eichenwalde', 'COMMON'),
       (102, 'Eichenwalde', 'RARE'),
       (102, 'Eichenwalde', 'ULTRA_RARE'),
       (103, 'Temple of Anubis', 'COMMON'),
       (103, 'Temple of Anubis', 'RARE'),
       (103, 'Temple of Anubis', 'ULTRA_RARE'),
       (104, 'Black Forest', 'COMMON'),
       (104, 'Black Forest', 'RARE'),
       (104, 'Black Forest', 'ULTRA_RARE'),
       (105, 'Blizzard World', 'COMMON'),
       (105, 'Blizzard World', 'RARE'),
       (105, 'Blizzard World', 'ULTRA_RARE');
